service: hello-world

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
